language: emacs-lisp
group: deprecated-2017Q2



script:
  - evm install $EVM_EMACS --use --skip
  - evm list
  - /usr/bin/env python --version
  - /usr/bin/env python -c "import sys; print('\n'.join(sys.path))"
  - /usr/bin/env python -c "import os; print(os.environ['PATH'])"
  - echo $PATH
  - cask exec sh -c 'echo $PATH'
  - emacs --version
  - cask exec emacs --version
  - cask install
  - make test

env:
  matrix:
    - EVM_EMACS=emacs-24.4-travis
    - EVM_EMACS=emacs-24.5-travis
    - EVM_EMACS=emacs-25.1-travis
    - EVM_EMACS=emacs-25.2-travis
    - EVM_EMACS=emacs-25.3-travis    
    - EVM_EMACS=emacs-git-snapshot-travis
matrix:
  fast_finish: true
  allow_failures:
    - env: EVM_EMACS=emacs-git-snapshot-travis

before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh

notifications:
  email: false
